# arguments for dataset
dataset: gtav_syn
val_dataset: cityscapes
nclass: 19
crop_size: 768
train_split: ./split
val_split: ./split/val


# arguments for training
max_iters: 40000
interval: 4000
log_step: 50
batch_size: 2 # number of samples per GPU
lr: 0.0025  # 4GPUs
lr_multi: 10.0
criterion:
  name: DCCLoss
  kwargs:
    ignore_index: 255
seed: null

# arguments for model
backbone: resnet50
head: deeplabv3plus
freeze_bn: False
uncertainty: 0.0
pos: []
multi_grid: True
replace_stride_with_dilation: [False, True, True]
dilations: [12, 24, 36]